apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: keycloak
  dependsOn:
    - name: keycloak-db
      namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: keycloakx
      version: 7.1.5
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  values:
    # Keycloak startup command
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--hostname=https://auth.theedgeworks.ai"
      - "--proxy-headers=xforwarded"

    # Environment variables from secrets
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: password
      - name: JAVA_OPTS_APPEND
        value: "-XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError -Djava.awt.headless=true -Djgroups.dns.query=keycloak-keycloak-keycloakx-headless.keycloak.svc.cluster.local"

    # Database connection checker
    dbchecker:
      enabled: true
      image:
        repository: docker.io/busybox
        tag: "1.32"
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 32Mi

    # PostgreSQL database configuration
    database:
      vendor: postgres
      hostname: keycloak-postgresql
      port: 5432
      username: keycloak
      database: keycloak
      existingSecret: keycloak-db-credentials
      existingSecretKey: password

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        metallb.universe.tf/loadBalancerIP: "192.168.0.110"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      rules:
        - host: auth.theedgeworks.ai
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: keycloak-tls
          hosts:
            - auth.theedgeworks.ai

    # Resource limits
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

    # Health checks - use correct paths for Keycloak 26.x management interface
    health:
      enabled: true

    # Override default health probe paths (remove /auth prefix for management interface)
    startupProbe: |
      httpGet:
        path: /health
        port: http-internal
      initialDelaySeconds: 15
      periodSeconds: 5
      failureThreshold: 60
      timeoutSeconds: 1

    livenessProbe: |
      httpGet:
        path: /health/live
        port: http-internal
      periodSeconds: 10
      failureThreshold: 3
      timeoutSeconds: 5

    readinessProbe: |
      httpGet:
        path: /health/ready
        port: http-internal
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
      timeoutSeconds: 1
