apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: keycloakx
      version: 7.1.5
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  values:
    auth:
      adminUser: admin
      adminPassword: "ChangeMe123!"
    ingress:
      enabled: true
      hostname: auth.theedgeworks.ai
      annotations:
        kubernetes.io/ingress.class: traefik
    postgresql:
      enabled: true
      auth:
        postgresPassword: "ChangeMeDB123!"
