apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: keycloak
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: postgresql
      version: 18.1.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # See https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    global:
      postgresql:
        auth:
          username: dbusername
          password: dbpassword
          database: keycloak      