apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-db
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: keycloak
  dependsOn:
    - name: longhorn
      namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: 18.1.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          username: keycloak
          database: keycloak
          existingSecret: keycloak-db-credentials
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
