apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "6.24.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Deploy in single binary (monolithic) mode for simplicity
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      limits_config:
        retention_period: 720h  # 30 days

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
      persistence:
        enabled: true
        storageClass: longhorn
        size: 200Gi

    # Disable other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Disable gateway (not needed for single binary)
    gateway:
      enabled: false

    # Disable chunksCache, resultsCache for simplicity
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Enable ServiceMonitor for Prometheus scraping
    serviceMonitor:
      enabled: true

    # Disable test pod
    test:
      enabled: false
