apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-tenant
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s-cluster/apps/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: infra  # Wait for infra kustomization (which deploys minio-operator)
  wait: true
  timeout: 10m
