apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-tenant
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s-cluster/apps/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: minio-helmrepository
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
  timeout: 5m
