# Harbor Metrics Configuration
#
# Harbor has a dedicated exporter component that collects metrics from all Harbor
# components. This is the primary source of harbor_* metrics (artifact counts,
# project quotas, etc.).
#
# The registry component also exposes its own registry_* metrics on port 8001
# (HTTP request durations, in-flight requests, etc.).
#
# Note: core, jobservice, and trivy pods do NOT expose port 8001 for metrics.
# Only the exporter and registry expose metrics endpoints.
---
# PodMonitor for Harbor Exporter - main source of harbor_* metrics
# Uses PodMonitor because the service lacks the component label
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: harbor-exporter
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - harbor
  selector:
    matchLabels:
      app: harbor
      component: exporter
  podMetricsEndpoints:
    - targetPort: 8001
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# PodMonitor for Harbor Registry - exposes registry_* metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: harbor-registry
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - harbor
  selector:
    matchLabels:
      app: harbor
      component: registry
  podMetricsEndpoints:
    - targetPort: 8001
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
