apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: minio-operator
  chart:
    spec:
      chart: minio-operator
      version: 5.0.18
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      image:
        repository: quay.io/minio/operator
        tag: v5.0.17
        pullPolicy: IfNotPresent
      replicaCount: 1  
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      env:
        - name: OPERATOR_STS_ENABLED
          value: "on"
        - name: MINIO_CONSOLE_TLS_ENABLE
          value: "off"
    console:
      enabled: true
      image:
        repository: quay.io/minio/operator  
        tag: v5.0.17
        pullPolicy: IfNotPresent
    # Remove tenant configuration from operator values
    # Tenants should be deployed separately using Tenant CRD
