apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-operator

resources:
  - namespace.yaml
  - helmrepository.yaml
  - operator-helmrelease.yaml

# MinIO Operator HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: "4.5.8"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
