apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: minio-operator
  chart:
    spec:
      chart: minio-operator
      version: 6.0.4
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      image:
        repository: quay.io/minio/operator
        tag: v6.0.4
        pullPolicy: IfNotPresent
      resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    console:
      image:
        repository: quay.io/minio/console
        tag: v6.0.4
        pullPolicy: IfNotPresent
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
          limits:
    tenants: []
