apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: minio-operator
  chart:
    spec:
      chart: minio-operator
      version: 4.3.7
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: minio/operator
      tag: v5.0.18
      pullPolicy: IfNotPresent
    replicaCount: 1  
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    tenants:
      - name: minio-tenant
        namespace: minio-tenant
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2024-05-10T01-41-38Z.arm64
          pullPolicy: IfNotPresent
        pools:
          - servers: 2
            name: pool-0
            volumesPerServer: 2
            volumeClaimTemplate:
              metadata:
                name: data
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 300Gi
                storageClassName: local-path
        mountPath: /export
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: username
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: password
        exposeServices:
          console: true
          minio: true
        podManagementPolicy: Parallel
        requestAutoCert: false
