apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: minio-operator
  chart:
    spec:
      chart: minio-operator
      version: 4.3.7
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: quay.io/minio/operator
      tag: v4.3.7
      pullPolicy: IfNotPresent
    replicaCount: 1
    
    # ARM64 node selector
    nodeSelector:
      kubernetes.io/arch: arm64
    
    # Tolerations for ARM64 nodes (if needed)
    tolerations: []
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
