apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: forgejo
  dependsOn:
    - name: forgejo-db
      namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "16.1.0"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 200Gi

    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: code.theedgeworks.ai
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: forgejo-tls
          hosts:
            - code.theedgeworks.ai

    gitea:
      admin:
        existingSecret: forgejo-admin-secret

      config:
        database:
          DB_TYPE: postgres
          HOST: forgejo-postgresql.forgejo.svc.cluster.local
          PORT: "5432"
          NAME: forgejo
          USER: forgejo
        server:
          ROOT_URL: https://code.theedgeworks.ai
          DOMAIN: code.theedgeworks.ai
          SSH_DOMAIN: code.theedgeworks.ai

      additionalConfigFromEnvs:
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-db-credentials
              key: password

      oauth:
        - name: Keycloak
          provider: openidConnect
          autoDiscoverUrl: https://auth.theedgeworks.ai/realms/theedgeworks/.well-known/openid-configuration
          existingSecret: forgejo-oidc-secret

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
