apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opentelemetry-manifests
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/ramaedge/opentelemetry-manifests.git
