apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpi-data
  namespace: devpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
