apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: claude-runner-set
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    runnerScaleSetName: claude-runner-set
    # GitHub configuration
    githubConfigUrl: "https://github.com/ramaedge"
    # Reference to pre-existing secret in arc-runners namespace
    # Secret must have key: github_token
    githubConfigSecret: arc-runner-set-secret
    
    # Auto-scaling configuration
    minRunners: 0
    maxRunners: 10
    
    # Runner pod template
    template:
      spec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: runner
            image: harbor.theedgeworks.ai/base/actions-runner-claude:v0.3.3
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
              limits:
                cpu: "2"
                memory: "4Gi"
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        
        # Persistent storage for workspace using Longhorn
        # Each runner pod gets its own PVC via ephemeral volumeClaimTemplate
        volumes:
          - name: work
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 5Gi
