apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-tenant

resources:
  - minio-simple.yaml

configMapGenerator:
  - name: minio-config
    literals:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio123
