apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z.arm64
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      size: 300Gi
      storageClassName: local-path
  mountPath: /export
  env:
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: username
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: password
  exposeServices:
    console: true
    minio: true
  podManagementPolicy: Parallel
  requestAutoCert: false 