apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
  imagePullPolicy: IfNotPresent
  pools:
    - servers: 3
      name: pool-0
      volumesPerServer: 2
      # ARM64 node selector (at pool level)
      nodeSelector:
        kubernetes.io/arch: arm64
      # Tolerations for ARM64 nodes (if needed)
      tolerations: []
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
          storageClassName: longhorn
  mountPath: /export
  podManagementPolicy: Parallel
  requestAutoCert: false
  configuration:
    name: storage-configuration
  env:
    - name: MINIO_SERVER_URL
      value: "https://storage.theedgeworks.ai"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://storage-console.theedgeworks.ai" 
  exposeServices:
    console: true
    minio: true
  features:
    bucketDNS: false
