apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z.arm64
  imagePullPolicy: IfNotPresent
  pools:
    - name: pool-0
      servers: 2
      volumesPerServer: 2
      # ARM64 node selector (at pool level)
      nodeSelector:
        kubernetes.io/arch: arm64
      # Tolerations for ARM64 nodes (if needed)
      tolerations: []
      # Resource limits for Raspberry Pi (at pool level)
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
          storageClassName: local-path
  mountPath: /export
  podManagementPolicy: Parallel
  requestAutoCert: false
  env:
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: username
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: password
    
    # Google Workspace OIDC Configuration
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://accounts.google.com/.well-known/openid_configuration"
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: minio-google-workspace-oidc
          key: client-id
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: minio-google-workspace-oidc
          key: client-secret
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "email"
    - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
      value: "on"
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
      value: "on"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email"
    - name: MINIO_IDENTITY_OPENID_CLAIM_PREFIX
      value: "google"
  exposeServices:
    console: true
    minio: true
  features:
    bucketDNS: false