apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: harbor
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: harbor
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    externalURL: https://harbor.ramaedge.local
    imagePullPolicy: IfNotPresent
    
    # Use ARM-based images
    core:
      image:
        repository: mikrobithu/harbor-core
        tag: dev-arm
    portal:
      image:
        repository: mikrobithu/harbor-portal
        tag: dev-arm
    jobservice:
      image:
        repository: mikrobithu/harbor-jobservice
        tag: dev-arm
    registry:
      registry:
        image:
          repository: mikrobithu/registry-photon
          tag: dev-arm
      controller:
        image:
          repository: mikrobithu/harbor-registryctl
          tag: dev-arm
    nginx:
      image:
        repository: mikrobithu/nginx-photon
        tag: dev-arm

    # External PostgreSQL configuration
    database:
      type: external
      external:
        host: postgres-service.harbor.svc.cluster.local
        port: 5432
        username: harbor
        passwordSecretRef:
          name: harbor-db-credentials
          key: password
        coreDatabase: harbor
        sslmode: disable

    # External Redis configuration
    redis:
      type: external
      external:
        addr: redis-service.harbor.svc.cluster.local:6379
        passwordSecretRef:
          name: harbor-redis-credentials
          key: password
      internal:
        enabled: false
      harborRedis:
        enabled: false

    # Persistence configuration
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          size: 10Gi
        jobservice:
          size: 1Gi

    # TLS configuration
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.ramaedge.local
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure

    # Disable components we don't need
    chartmuseum:
      enabled: false
    trivy:
      enabled: false
    notary:
      enabled: false 