apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    # Add your Harbor Helm values here
    externalURL: https://harbor.ramaedge.local
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          size: 10Gi
        chartmuseum:
          size: 5Gi
        jobservice:
          size: 1Gi
        database:
          size: 1Gi
        redis:
          size: 1Gi
    database:
      external:
        host: postgres
        port: 5432
        username: harbor
        passwordSecretRef:
          name: harbor-db-credentials
          key: password
        database: harbor
    redis:
      external:
        host: redis
        port: 6379 